### PR TITLE
add checkbox to toggle grid

### PR DESCRIPTION
**Pull request by jpalmieri**
https://user-images.githubusercontent.com/4692673/111260970-f4ba0e00-85de-11eb-99aa-5ca647de9fb1.mov

### CODE REVIEW

**Comment by jpalmieri** [comment]
Sorry! This was meant for my fork :)

**Comment by jpalmieri** [comment]
PS: love your work!

**Comment by jobtalle** [comment]
Oh, would love to merge this feature though!

**Comment by jpalmieri** [comment]
ok, cool! I'll reopen then 😄

**Comment by jpalmieri** [comment]
@jobtalle Let me know if you have ideas about the interface, e.g., where the checkbox should go.

**Comment by jobtalle** [comment]
This looks good as is :)

**Pull request merged**
